// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx-iDzjqd3QCUtgZlWn0vzoDeBgMv7onk',
    appId: '1:873718840033:web:a7fa72dc4d18ec611615a0',
    messagingSenderId: '873718840033',
    projectId: 'dozy-c3e50',
    authDomain: 'dozy-c3e50.firebaseapp.com',
    storageBucket: 'dozy-c3e50.firebasestorage.app',
    measurementId: 'G-6589CTN2B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7jlw6CYF41-YxQ6fuclS6Fbnk8K5-Hno',
    appId: '1:873718840033:android:bb73fe821032f2bd1615a0',
    messagingSenderId: '873718840033',
    projectId: 'dozy-c3e50',
    storageBucket: 'dozy-c3e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACcYnIU-2eLTRYP4Vh0lEHL59oZVwrU48',
    appId: '1:873718840033:ios:6b2cb533de792fb11615a0',
    messagingSenderId: '873718840033',
    projectId: 'dozy-c3e50',
    storageBucket: 'dozy-c3e50.firebasestorage.app',
    iosBundleId: 'com.example.dozy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACcYnIU-2eLTRYP4Vh0lEHL59oZVwrU48',
    appId: '1:873718840033:ios:6b2cb533de792fb11615a0',
    messagingSenderId: '873718840033',
    projectId: 'dozy-c3e50',
    storageBucket: 'dozy-c3e50.firebasestorage.app',
    iosBundleId: 'com.example.dozy',
  );

}